# Generated by Django 4.2.28 on 2026-02-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internintelligence',
            name='risk_flags',
            field=models.JSONField(default=list, help_text='Risk indicators (low engagement, skill gaps, etc.)'),
        ),
        migrations.AlterField(
            model_name='resumefeature',
            name='skill_vector',
            field=models.JSONField(default=dict, help_text='Binary encoding of skills (present/not present)'),
        ),
    ]
