# Generated by Django 4.2.28 on 2026-02-13 07:55

import apps.analytics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0007_remove_old_intern_analysis_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='pdf_report',
            field=models.FileField(blank=True, help_text='Weekly report PDF file', null=True, upload_to=apps.analytics.models.WeeklyReport._get_pdf_upload_path),
        ),
        migrations.CreateModel(
            name='InternIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.FloatField(default=0.0, help_text='Technical skills proficiency score')),
                ('leadership_score', models.FloatField(default=0.0, help_text='Leadership and management potential score')),
                ('communication_score', models.FloatField(default=0.0, help_text='Communication skills score')),
                ('culture_fit_score', models.FloatField(default=0.0, help_text='Cultural fit assessment score')),
                ('ai_readiness_score', models.FloatField(default=0.0, help_text='Readiness for AI-assisted work score')),
                ('predicted_growth_score', models.FloatField(default=0.0, help_text='Predicted growth trajectory score')),
                ('skill_profile', models.JSONField(default=dict, help_text='Detailed skill breakdown by category')),
                ('domain_strengths', models.JSONField(default=list, help_text='List of strongest domain areas')),
                ('skill_gaps', models.JSONField(default=list, help_text='Identified skill gaps')),
                ('recommendations', models.JSONField(default=list, help_text='Personalized development recommendations')),
                ('risk_flags', models.JSONField(default=list, help_text='Risk indicators')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_intelligence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intern Intelligence',
                'verbose_name_plural': 'Intern Intelligence',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
