# Generated by Django 4.2.28 on 2026-02-13 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0008_alter_weeklyreport_pdf_report_internintelligence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField(blank=True, help_text='Parsed resume text')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('TECHNICAL_ROUND', 'Technical Round'), ('HR_ROUND', 'HR Round'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(help_text='Job role title (e.g., FRONTEND_DEVELOPER, BACKEND_DEVELOPER)', max_length=100, unique=True)),
                ('role_description', models.TextField(blank=True, help_text='Detailed role description')),
                ('mandatory_skills', models.JSONField(default=list, help_text='List of required mandatory skills')),
                ('preferred_skills', models.JSONField(default=list, help_text='List of preferred/nice-to-have skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['role_title'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_match_ratio', models.FloatField(default=0.0, help_text='Ratio of matched skills to required skills (0-1)')),
                ('mandatory_skill_coverage', models.BooleanField(default=False, help_text='Whether all mandatory skills are present')),
                ('domain_similarity_score', models.FloatField(default=0.0, help_text='Similarity between candidate domain and job domain (0-1)')),
                ('skill_depth_score', models.FloatField(default=0.0, help_text='Depth/level of each skill (0-1)')),
                ('skill_project_consistency', models.FloatField(default=0.0, help_text='Consistency between skills and projects (0-1)')),
                ('critical_skill_gap_count', models.IntegerField(default=0, help_text='Number of critical skills missing')),
                ('degree_level_encoded', models.IntegerField(default=1, help_text='1=High School, 2=Bachelor, 3=Masters+')),
                ('gpa_normalized', models.FloatField(default=0.0, help_text='Normalized GPA score (0-1)')),
                ('university_tier_score', models.FloatField(default=0.0, help_text='University ranking score (0-1)')),
                ('coursework_relevance_score', models.FloatField(default=0.0, help_text='Relevance of coursework to role (0-1)')),
                ('experience_duration_months', models.IntegerField(default=0, help_text='Total experience in months')),
                ('internship_relevance_score', models.FloatField(default=0.0, help_text='Relevance of internship experience (0-1)')),
                ('open_source_score', models.FloatField(default=0.0, help_text='Open source contribution score (0-1)')),
                ('hackathon_count', models.IntegerField(default=0, help_text='Number of hackathons attended')),
                ('project_count', models.IntegerField(default=0, help_text='Number of projects')),
                ('project_complexity_score', models.FloatField(default=0.0, help_text='Complexity of projects (0-1)')),
                ('quantified_impact_presence', models.BooleanField(default=False, help_text='Whether projects have quantifiable impact')),
                ('production_tools_usage_score', models.FloatField(default=0.0, help_text='Usage of production tools (0-1)')),
                ('github_activity_score', models.FloatField(default=0.0, help_text='GitHub activity level (0-1)')),
                ('keyword_stuffing_ratio', models.FloatField(default=0.0, help_text='Ratio of keywords to content (0-1)')),
                ('writing_clarity_score', models.FloatField(default=0.0, help_text='Clarity of writing (0-1)')),
                ('action_verb_density', models.FloatField(default=0.0, help_text='Density of action verbs (0-1)')),
                ('resume_consistency_score', models.FloatField(default=0.0, help_text='Overall consistency (0-1)')),
                ('resume_length_normalized', models.FloatField(default=0.0, help_text='Normalized resume length (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_features', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Resume Feature',
                'verbose_name_plural': 'Resume Features',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model name', max_length=100)),
                ('model_version', models.CharField(help_text='Version string', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of training samples')),
                ('training_accuracy', models.FloatField(default=0.0, help_text='Training accuracy')),
                ('roc_auc', models.FloatField(default=0.0, help_text='ROC-AUC score')),
                ('f1_score', models.FloatField(default=0.0, help_text='F1 score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Registry',
                'verbose_name_plural': 'Model Registries',
                'ordering': ['-created_at'],
                'unique_together': {('model_name', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_score', models.FloatField(default=0.0, help_text='Overall suitability (0-1)')),
                ('technical_competency_score', models.FloatField(default=0.0, help_text='Technical skills (0-1)')),
                ('growth_potential_score', models.FloatField(default=0.0, help_text='Growth potential (0-1)')),
                ('resume_authenticity_score', models.FloatField(default=0.0, help_text='Resume authenticity (0-1)')),
                ('communication_score', models.FloatField(default=0.0, help_text='Communication skills (0-1)')),
                ('leadership_score', models.FloatField(default=0.0, help_text='Leadership potential (0-1)')),
                ('decision', models.CharField(blank=True, choices=[('INTERVIEW_SHORTLIST', 'Interview Shortlist'), ('TECHNICAL_ASSIGNMENT', 'Technical Assignment'), ('MANUAL_REVIEW', 'Manual Review'), ('REJECT', 'Reject')], help_text='ML prediction decision', max_length=30)),
                ('model_version', models.CharField(blank=True, help_text='Version of model used for prediction', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Model confidence (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Model Prediction',
                'verbose_name_plural': 'Model Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted', models.BooleanField(default=False, help_text='Was candidate shortlisted')),
                ('technical_assignment_score', models.FloatField(blank=True, help_text='Technical test score', null=True)),
                ('hr_feedback_score', models.FloatField(blank=True, help_text='HR round feedback (0-1)', null=True)),
                ('hired', models.BooleanField(default=False, help_text='Was candidate hired')),
                ('offer_extended', models.BooleanField(default=False, help_text='Was offer given')),
                ('offer_accepted', models.BooleanField(default=False, help_text='Was offer accepted')),
                ('final_suitability_label', models.BooleanField(default=False, help_text='Final label for model training')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_outcome', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Hiring Outcome',
                'verbose_name_plural': 'Hiring Outcomes',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowthTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_since_joining', models.IntegerField(default=0, help_text='Months employed')),
                ('performance_rating', models.FloatField(default=0.0, help_text='Performance rating (0-5)')),
                ('skill_growth_score', models.FloatField(default=0.0, help_text='Skill improvement (0-1)')),
                ('manager_feedback_score', models.FloatField(default=0.0, help_text='Manager rating (0-1)')),
                ('retention_status', models.BooleanField(default=True, help_text='Still employed')),
                ('promotion_received', models.BooleanField(default=False, help_text='Was promoted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='growth_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Growth Tracking',
                'verbose_name_plural': 'Growth Tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_project_mismatch_ratio', models.FloatField(default=0.0, help_text='Mismatch ratio between skills and projects (0-1)')),
                ('excessive_skill_listing_flag', models.BooleanField(default=False, help_text='Too many skills flag')),
                ('duplicate_bullet_pattern_flag', models.BooleanField(default=False, help_text='Duplicate patterns flag')),
                ('authenticity_label', models.BooleanField(default=True, help_text='Is resume authentic')),
                ('reviewed_by', models.CharField(blank=True, help_text='Reviewer name', max_length=100)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticity_review', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Authenticity Review',
                'verbose_name_plural': 'Authenticity Reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='analytics.jobrole'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('intern', 'job_role')},
        ),
    ]
