# Generated by Django 4.2.28 on 2026-02-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_new_ml_pipeline_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktracking',
            name='complexity',
        ),
    ]
