# Generated by Django 4.2.28 on 2026-02-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_tasktracking_project_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('impact', models.TextField(blank=True, help_text='Quantified impact or key results')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_projects', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Resume Project',
                'verbose_name_plural': 'Resume Projects',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, help_text='ISO format or text', max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('is_internship', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_experience', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Resume Experience',
                'verbose_name_plural': 'Resume Experiences',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('honors', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_education', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Resume Education',
                'verbose_name_plural': 'Resume Education Entries',
            },
        ),
        migrations.CreateModel(
            name='ResumeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_certifications', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Resume Certification',
                'verbose_name_plural': 'Resume Certifications',
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Normalized skill name (e.g., Python)', max_length=100)),
                ('category', models.CharField(help_text='Skill category (e.g., programming_languages, frameworks_libraries)', max_length=50)),
                ('is_major', models.BooleanField(default=False, help_text='Whether this is a primary skill for the role')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_skills', to='analytics.application')),
            ],
            options={
                'verbose_name': 'Resume Skill',
                'verbose_name_plural': 'Resume Skills',
                'unique_together': {('application', 'name', 'category')},
            },
        ),
    ]
