# Generated by Django 4.2.28 on 2026-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_resumeproject_resumeexperience_resumeeducation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='honors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='start_date',
            field=models.CharField(blank=True, help_text='ISO format or text', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeskill',
            name='category',
            field=models.CharField(blank=True, help_text='Skill category (e.g., programming_languages, frameworks_libraries)', max_length=50, null=True),
        ),
    ]
