# Generated by Django 4.2.28 on 2026-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_resumeeducation_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecertification',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumecertification',
            name='issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumeproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeproject',
            name='impact',
            field=models.TextField(blank=True, help_text='Quantified impact or key results', null=True),
        ),
    ]
