# Generated by Django 4.2.28 on 2026-03-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmodule'),
        ('analytics', '0017_rl_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracking',
            name='project_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectmodule'),
        ),
    ]
