# Generated by Django 4.2.28 on 2026-03-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_tasktracking_project_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracking',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text='List of skill names developed by this task'),
        ),
    ]
