# Generated by Django 4.2.28 on 2026-04-21 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0022_phase1_v2_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_cert_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for public verification', unique=True)),
                ('cert_type', models.CharField(choices=[('PHASE_1', 'Internship Completion Certificate'), ('PHASE_2', 'Stipend Internship Certificate'), ('PPO', 'Pre-Placement Offer Certificate')], max_length=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('overall_score_at_issue', models.FloatField()),
                ('scores_snapshot', models.JSONField(default=dict, help_text='Full breakdown of metrics at the time of issuance')),
                ('criteria_snapshot', models.JSONField(default=dict, help_text='Snapshot of the gate criteria used for this certificate')),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('phase_evaluation', models.OneToOneField(help_text='Evaluation that triggered this certificate', on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='analytics.phaseevaluation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification Record',
                'verbose_name_plural': 'Certification Records',
                'ordering': ['-issue_date'],
            },
        ),
    ]
