# Generated by Django 4.2.28 on 2026-04-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0023_certificationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('week_number', models.IntegerField()),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('tasks_assigned', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_in_progress', models.IntegerField(default=0)),
                ('tasks_overdue', models.IntegerField(default=0)),
                ('avg_task_quality_rating', models.FloatField(blank=True, null=True)),
                ('total_estimated_hours', models.FloatField(default=0)),
                ('total_actual_hours', models.FloatField(default=0)),
                ('hour_variance_pct', models.FloatField(blank=True, null=True)),
                ('attendance_days', models.IntegerField(default=0)),
                ('expected_days', models.IntegerField(default=5)),
                ('late_check_ins', models.IntegerField(default=0)),
                ('attendance_pct', models.FloatField(default=0.0)),
                ('productivity_score', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('growth_score', models.FloatField(blank=True, null=True)),
                ('overall_weekly_score', models.FloatField(blank=True, null=True)),
                ('productivity_delta', models.FloatField(blank=True, null=True)),
                ('quality_delta', models.FloatField(blank=True, null=True)),
                ('overall_delta', models.FloatField(blank=True, null=True)),
                ('cumulative_overall_score', models.FloatField(blank=True, null=True)),
                ('ai_narrative', models.TextField(blank=True)),
                ('ai_top_achievement', models.CharField(blank=True, max_length=500)),
                ('ai_concern_area', models.CharField(blank=True, max_length=500)),
                ('ai_growth_note', models.CharField(blank=True, max_length=500)),
                ('red_flag', models.BooleanField(default=False)),
                ('red_flag_reasons', models.JSONField(default=list)),
                ('self_report_mismatch', models.BooleanField(default=False)),
                ('self_report_mismatch_details', models.JSONField(default=list)),
                ('manager_reviewed', models.BooleanField(default=False)),
                ('manager_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports_v2', to=settings.AUTH_USER_MODEL)),
                ('intern_self_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_counterpart', to='analytics.weeklyreportv2')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Report V2',
                'verbose_name_plural': 'Weekly Reports V2',
                'ordering': ['-week_start'],
                'unique_together': {('intern', 'week_start', 'is_auto_generated')},
            },
        ),
    ]
