# Generated by Django 4.2.28 on 2026-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_add_conversion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='department',
            field=models.CharField(blank=True, help_text='Department this role belongs to (e.g., Engineering, Marketing)', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificationcriteria',
            name='description',
            field=models.TextField(help_text='Human-readable explanation of this criteria set'),
        ),
    ]
