# Generated by Django 4.2.28 on 2026-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_jobrole_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreportv2',
            name='ai_quote',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='weeklyreportv2',
            name='ai_work_summary',
            field=models.TextField(blank=True),
        ),
    ]
