# Generated by Django 4.2.28 on 2026-03-12 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_rl_models'),
        ('feedback', '0002_feedback_updated_at_alter_feedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='analytics.tasktracking'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED_APPROVED', 'Complete - Approved'), ('COMPLETED_REWORK', 'Complete - Needs Rework')], help_text='Status of the task being reviewed', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly Check-in'), ('PROJECT', 'Project Review'), ('MID_TERM', 'Mid-term Evaluation'), ('FINAL', 'Final Evaluation'), ('MANAGER_REVIEW', 'Manager Review'), ('TASK', 'Task Feedback')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
