# Generated by Django 4.2.30 on 2026-06-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_resumedata_applied_role_and_more'),
        ('feedback', '0003_add_task_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='evidences',
            field=models.ManyToManyField(blank=True, help_text='Documents uploaded as evidence for this feedback', related_name='feedback_evidences', to='documents.document'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent_feedback',
            field=models.ForeignKey(blank=True, help_text='The parent feedback if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback'),
        ),
    ]
