# Generated by Django 4.2.30 on 2026-06-29 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0028_tasktracking_evidences_tasktracking_parent_task'),
        ('feedback', '0004_feedback_evidences_feedback_parent_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('evidences', models.ManyToManyField(blank=True, related_name='task_comment_evidences', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analytics.tasktracking')),
            ],
        ),
    ]
