"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from redmail import EmailSender

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR resolves to the backend/ directory (parent of core/ config package)
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from multiple possible locations (settings dir, project root)
env_paths = [
    os.path.join(os.path.dirname(__file__), '.env'),
    os.path.join(BASE_DIR, '.env'),
    os.path.join(BASE_DIR.parent, '.env'),
]
for env_path in env_paths:
    if os.path.exists(env_path):
        load_dotenv(env_path, override=True)

# Unset system-level GITHUB_TOKEN to avoid conflicts with AI_TALENT_GITHUB_TOKEN
if 'GITHUB_TOKEN' in os.environ:
    del os.environ['GITHUB_TOKEN']

# GitHub Models Token for LLM Parsing
AI_TALENT_GITHUB_TOKEN = os.getenv('AI_TALENT_GITHUB_TOKEN')
HF_TOKEN = os.getenv('HF_TOKEN')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from environment variable DJANGO_SECRET_KEY
# DEBUG value should always come from environment


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.accounts",
    "apps.interns",
    "apps.documents",
    "apps.assessments",
    "apps.feedback",
    "apps.analytics",
    "apps.roles",
    "apps.system",
    "apps.projects",
    "apps.notifications",
    "corsheaders",
    'rest_framework',
    'django_celery_beat',
]

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# =============================================================================
# JWT Settings (djangorestframework-simplejwt)
# =============================================================================
# Use a separate JWT_SECRET_KEY that is at least 32 bytes (64 hex chars)
# for HS256 algorithm. This is more secure than reusing Django's SECRET_KEY.
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', os.getenv('DJANGO_SECRET_KEY', ''))

# Ensure JWT secret is at least 32 bytes for SHA256
if len(JWT_SECRET_KEY) < 32:
    import secrets
    # Generate a secure 32-byte key if not provided or too short
    JWT_SECRET_KEY = secrets.token_hex(32)
    print(f"WARNING: JWT_SECRET_KEY was too short. Generated a new secure key. Add JWT_SECRET_KEY to .env for persistence.")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 60))),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 1440))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}

RATELIMIT_USE_CACHE = 'default'

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DJANGO_DEBUG") == "True"
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")
if DEBUG:
    ALLOWED_HOSTS.append("*")

# =============================================================================
# Website Branding Settings
# =============================================================================
SITE_NAME = "AIMs"
SITE_HEADER = "AIMs Talent Intelligence"
SITE_TITLE = "AIMs - Advanced Intern Management System"
INDEX_TITLE = "Welcome to AIMs - Advanced Intern Management System"

# ==============================================================================
# PHASE 2 — CERTIFICATION ENGINE SETTINGS
# ==============================================================================

# WeasyPrint — base URL for resolving relative CSS/image URLs inside templates
WEASYPRINT_BASEURL = BASE_DIR / 'apps' / 'analytics' / 'templates'

# Certificate PDF storage
CERTIFICATE_STORAGE_PATH = BASE_DIR / 'media' / 'certificates'

# Frontend base URL — used to build /verify/{uuid}/ QR code links
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:5173')

# Company branding for certificates
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'AIMS Technologies')
COMPANY_LOGO_URL = os.environ.get('COMPANY_LOGO_URL', '') 


# ==============================================================================
# PHASE 3 — WEEKLY REPORT ENGINE SETTINGS
# ==============================================================================
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL   = 'llama3-8b-8192'

# Celery configuration adjustments
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files (Uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174"
).split(",")

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# =============================================================================
# Email Settings (SMTP)
# =============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# =============================================================================
# Red Mail Configuration
# =============================================================================
from jinja2 import Environment, FileSystemLoader
EMAIL_SENDER = EmailSender(
    host=os.getenv('EMAIL_HOST', 'smtp.gmail.com'),
    port=int(os.getenv('EMAIL_PORT', 587)),
    username=os.getenv('EMAIL_HOST_USER'),
    password=os.getenv('EMAIL_HOST_PASSWORD'),
    use_starttls=os.getenv('EMAIL_USE_TLS', 'True') == 'True'
)
EMAIL_SENDER.sender = f"AIMs Talent Platform <{os.getenv('EMAIL_HOST_USER')}>"
EMAIL_SENDER.use_jinja = False
