# Generated by Django 4.2.28 on 2026-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('INTERN_ASSIGNED', 'Intern Assigned'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_SUBMITTED', 'Task Submitted'), ('TASK_EVALUATED', 'Task Evaluated'), ('TASK_COMPLETED', 'Task Completed'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('FEEDBACK_GIVEN', 'Feedback Given'), ('REPORT_UPLOADED', 'Report Uploaded'), ('EVALUATION_DUE', 'Evaluation Due'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('STATUS_MISMATCH', 'Status Mismatch'), ('ENGAGEMENT_RISK', 'Engagement Risk'), ('MISSING_REPORT', 'Missing Report'), ('SYSTEM', 'System Notification')], default='INFO', max_length=30),
        ),
    ]
