# Generated by Django 4.2.30 on 2026-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('INTERN_ASSIGNED', 'Intern Assigned'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_SUBMITTED', 'Task Submitted'), ('TASK_EVALUATED', 'Task Evaluated'), ('TASK_COMPLETED', 'Task Completed'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('FEEDBACK_GIVEN', 'Feedback Given'), ('REPORT_UPLOADED', 'Report Uploaded'), ('EVALUATION_DUE', 'Evaluation Due'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('STATUS_MISMATCH', 'Status Mismatch'), ('ENGAGEMENT_RISK', 'Engagement Risk'), ('MISSING_REPORT', 'Missing Report'), ('SYSTEM', 'System Notification'), ('CERTIFICATE_GENERATED', 'Certificate Generated'), ('EVALUATION_COMPLETED', 'Evaluation Completed'), ('PROMOTION_SUCCESS', 'Promotion Success'), ('OFFER_ISSUED', 'PPO Offer Issued'), ('OFFER_RESPONSE', 'PPO Offer Response')], default='INFO', max_length=30),
        ),
    ]
