# Generated by Django 6.0.2 on 2026-02-11 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly Check-in'), ('PROJECT', 'Project Review'), ('MID_TERM', 'Mid-term Evaluation'), ('FINAL', 'Final Evaluation'), ('MANAGER_REVIEW', 'Manager Review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
