# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internprofile',
            name='resume',
        ),
    ]
