# Generated by Django 4.2.28 on 2026-02-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_remove_internprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Candidate location/city', max_length=255),
        ),
    ]
