"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from redmail import EmailSender

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR resolves to the backend/ directory (parent of core/ config package)
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from multiple possible locations (settings dir, project root)
default_env_paths = [
    os.path.join(os.path.dirname(__file__), '.env'),
    os.path.join(BASE_DIR, '.env'),
    os.path.join(BASE_DIR.parent, '.env'),
]

# Load default environment configuration
for env_path in default_env_paths:
    if os.path.exists(env_path):
        load_dotenv(env_path, override=True)
        break

# If DJANGO_ENV is set to production, load production overrides on top
django_env = os.environ.get('DJANGO_ENV', 'development').lower()
if django_env == 'production':
    prod_env_paths = [
        os.path.join(os.path.dirname(__file__), '.env.production'),
        os.path.join(BASE_DIR, '.env.production'),
        os.path.join(BASE_DIR.parent, '.env.production'),
    ]
    for env_path in prod_env_paths:
        if os.path.exists(env_path):
            load_dotenv(env_path, override=True)
            break

# Unset system-level GITHUB_TOKEN to avoid conflicts with AI_TALENT_GITHUB_TOKEN
if 'GITHUB_TOKEN' in os.environ:
    del os.environ['GITHUB_TOKEN']

# GitHub Models Token for LLM Parsing
AI_TALENT_GITHUB_TOKEN = os.getenv('AI_TALENT_GITHUB_TOKEN')
HF_TOKEN = os.getenv('HF_TOKEN')
REQUIRE_TASK_SKILLS = os.getenv('REQUIRE_TASK_SKILLS', 'True').lower() in ('true', '1', 't')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from environment variable DJANGO_SECRET_KEY
# DEBUG value should always come from environment


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.accounts",
    "apps.interns",
    "apps.documents",
    "apps.assessments",
    "apps.feedback",
    "apps.analytics",
    "apps.roles",
    "apps.system",
    "apps.projects",
    "apps.notifications",
    "corsheaders",
    'rest_framework',
    'django_celery_beat',
    'core',
]

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.accounts.authentication.FingerprintedJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Explicitly set global default — views override per-class with AllowAny.
    # Without this, DRF silently defaults to IsAuthenticated which conflicts
    # with views that declare AllowAny but are rejected by the JWT authenticator
    # before permission checks run.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# =============================================================================
# JWT Settings (djangorestframework-simplejwt)
# =============================================================================
# Use a separate JWT_SECRET_KEY that is at least 32 bytes (64 hex chars)
# for HS256 algorithm. This is more secure than reusing Django's SECRET_KEY.
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', os.getenv('DJANGO_SECRET_KEY', ''))

# Ensure JWT secret is at least 32 bytes for SHA256
if len(JWT_SECRET_KEY) < 32:
    import secrets
    # Generate a secure 32-byte key if not provided or too short
    JWT_SECRET_KEY = secrets.token_hex(32)
    print(f"WARNING: JWT_SECRET_KEY was too short. Generated a new secure key. Add JWT_SECRET_KEY to .env for persistence.")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 60))),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 1440))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'core.middleware.payload_encryption_middleware.PayloadEncryptionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=f"postgres://{os.getenv('POSTGRES_USER')}:{os.getenv('POSTGRES_PASSWORD')}@{os.getenv('POSTGRES_HOST')}:{os.getenv('POSTGRES_PORT')}/{os.getenv('POSTGRES_DB')}",
        conn_max_age=600
    )
}

RATELIMIT_USE_CACHE = 'default'

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DJANGO_DEBUG") == "True"
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,.vercel.app").split(",")
if DEBUG:
    ALLOWED_HOSTS.append("*")

# =============================================================================
# Website Branding Settings
# =============================================================================
SITE_NAME = "AIMs"
SITE_HEADER = "AIMs Talent Intelligence"
SITE_TITLE = "AIMs - Advanced Intern Management System"
INDEX_TITLE = "Welcome to AIMs - Advanced Intern Management System"

# ==============================================================================
# PHASE 2 — CERTIFICATION ENGINE SETTINGS
# ==============================================================================

# WeasyPrint — base URL for resolving relative CSS/image URLs inside templates
WEASYPRINT_BASEURL = BASE_DIR / 'apps' / 'analytics' / 'templates'

# Certificate PDF storage
CERTIFICATE_STORAGE_PATH = BASE_DIR / 'media' / 'certificates'

# Frontend base URL — used to build /verify/{uuid}/ QR code links
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:5173')

# Company branding for certificates
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'AIMS Technologies')
COMPANY_LOGO_URL = os.environ.get('COMPANY_LOGO_URL', '') 
SITE_NAME = os.environ.get('SITE_NAME', COMPANY_NAME)


# Celery configuration adjustments
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files (Uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# =============================================================================
# AWS S3 Storage Settings
# =============================================================================
USE_AWS_S3 = os.getenv('USE_AWS_S3', 'False') == 'True'

AWS_REGION              = os.getenv('AWS_REGION', 'us-east-1')
AWS_BUCKET_NAME         = os.getenv('AWS_BUCKET_NAME', '')
AWS_ACCESS_KEY_ID       = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY   = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_SESSION_TOKEN       = os.getenv('AWS_SESSION_TOKEN', '')      # Optional
AWS_CLOUDFRONT_BASE_URL = os.getenv('AWS_CLOUDFRONT_BASE_URL', '') # Optional CDN

if USE_AWS_S3:
    # Use django-storages S3Boto3Storage
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "region_name": AWS_REGION,
                "bucket_name": AWS_BUCKET_NAME,
                "security_token": AWS_SESSION_TOKEN if AWS_SESSION_TOKEN else None,
                "default_acl": "public-read",
                "custom_domain": AWS_CLOUDFRONT_BASE_URL if AWS_CLOUDFRONT_BASE_URL else f"{AWS_BUCKET_NAME}.s3.{AWS_REGION}.amazonaws.com",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174"
).split(",")

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "https://iconnect.cybersecurityumbrella.com,http://localhost:5173,http://127.0.0.1:5173"
).split(",")

CORS_EXPOSE_HEADERS = ['X-Encrypted', 'Content-Disposition', 'X-Session-Status']

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-encrypted',
    'x-accept-encrypted'
]

# Respect proxy headers under IIS Reverse Proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# =============================================================================
# Email Settings (SMTP)
# =============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'

# =============================================================================
# Red Mail Configuration
# =============================================================================
from jinja2 import Environment, FileSystemLoader
EMAIL_SENDER = EmailSender(
    host=os.getenv('EMAIL_HOST', 'smtp.gmail.com'),
    port=int(os.getenv('EMAIL_PORT', 587)),
    username=os.getenv('EMAIL_HOST_USER') or '',
    password=os.getenv('EMAIL_HOST_PASSWORD') or '',
    use_starttls=os.getenv('EMAIL_USE_TLS', 'True') == 'True'
)
EMAIL_SENDER.sender = f"AIMs Talent Platform <{os.getenv('EMAIL_HOST_USER')}>"
EMAIL_SENDER.use_jinja = False

# =============================================================================
# Cache Settings (Redis)
# =============================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "KEY_PREFIX": "aims",
        }
    }
}


# Trigger reload

# Reload after local.env change
