# Generated by Django 6.0.2 on 2026-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('RESUME', 'Resume'), ('GOVERNMENT_ID', 'Government ID'), ('ACADEMIC_CERTIFICATE', 'Academic Certificate'), ('INTERNSHIP_CERTIFICATE', 'Internship Certificate'), ('PROJECT_REPORT', 'Project Report'), ('PRESENTATION', 'Presentation'), ('CODE_REPO_LINK', 'Code Repository Link'), ('PROJECT_COMPLETION', 'Project Completion Evidence'), ('WEEKLY_PROGRESS', 'Weekly Progress Report'), ('TASK_SUBMISSION', 'Task Submission'), ('SELF_ASSESSMENT', 'Self Assessment Report'), ('RECOMMENDATION_LETTER', 'Recommendation Letter'), ('ACHIEVEMENT_CERTIFICATE', 'Achievement Certificate'), ('FEEDBACK_REPORT', 'Feedback Report'), ('PERFORMANCE_REVIEW', 'Performance Review'), ('MONTHLY_ASSESSMENT', 'Monthly Assessment'), ('PROJECT_ASSIGNMENT', 'Project Assignment Brief'), ('REQUIREMENT_DOC', 'Requirement Document'), ('SOP_GUIDELINES', 'SOP/Guidelines'), ('MENTOR_NOTES', 'Mentor Notes'), ('IMPROVEMENT_PLAN', 'Improvement Plan'), ('INTERNSHIP_POLICY', 'Internship Policy'), ('CODE_OF_CONDUCT', 'Code of Conduct'), ('NDA_TEMPLATE', 'NDA Template'), ('TALENT_REPORT', 'Talent Report'), ('ANALYTICS_EXPORT', 'Analytics Export'), ('AUDIT_LOG', 'Audit Log'), ('BULK_USER_UPLOAD', 'Bulk User Upload CSV'), ('ROLE_CONFIG', 'Role Configuration'), ('OFFER_LETTER', 'Offer Letter'), ('NDA', 'NDA'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
