# Generated by Django 6.0.2 on 2026-02-11

import apps.documents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file'),
        ('accounts', '0002_user_department'),
    ]

    operations = [
        # Add raw_text and is_parsed fields to Document model
        migrations.AddField(
            model_name='document',
            name='raw_text',
            field=models.TextField(blank=True, null=True, help_text='Extracted raw text from the document'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_parsed',
            field=models.BooleanField(default=False, help_text='Whether the document has been parsed'),
        ),
        
        # Create ResumeData model
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.JSONField(default=list, help_text='List of skills extracted from resume')),
                ('education', models.JSONField(default=list, help_text='List of education entries')),
                ('experience', models.JSONField(default=list, help_text='List of work experience entries')),
                ('projects', models.JSONField(default=list, help_text='List of projects')),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('tools', models.JSONField(default=list, help_text='List of tools and technologies')),
                ('total_experience_years', models.FloatField(default=0.0, help_text='Total years of experience')),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(limit_choices_to={'document_type': 'RESUME'}, on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Resume Data',
                'verbose_name_plural': 'Resume Data',
                'ordering': ['-parsed_at'],
            },
        ),
    ]
