# Generated by Django 4.2.28 on 2026-04-16 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('OFFERED', 'Offered'), ('ACTIVE_INTERN', 'Active Intern — Phase 1'), ('PHASE_1_COMPLETE', 'Phase 1 Complete'), ('STIPEND_INTERN', 'Stipend Intern — Phase 2'), ('PHASE_2_COMPLETE', 'Phase 2 Complete'), ('PPO_OFFERED', 'Pre-Placement Offer Issued'), ('FULL_TIME', 'Full-Time Employee'), ('NOT_CONVERTED', 'Not Converted'), ('FORMER', 'Former Intern')], default='ACTIVE_INTERN', max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_interns', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intern Profile',
                'verbose_name_plural': 'Intern Profiles',
            },
        ),
    ]
