# Generated by Django 4.2.28 on 2026-04-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_add_conversion_score'),
        ('accounts', '0003_add_intern_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued to intern'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('recommended_role_title', models.CharField(blank=True, max_length=200)),
                ('recommended_department', models.CharField(blank=True, max_length=200)),
                ('salary_band_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_band_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_onboarding_plan', models.TextField(blank=True)),
                ('ai_offer_summary', models.TextField(blank=True)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('intern_response_at', models.DateTimeField(blank=True, null=True)),
                ('intern_response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='analytics.conversionscore')),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_time_offer', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StipendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('HELD', 'On hold')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performance_score_at_disbursement', models.FloatField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stipends', to=settings.AUTH_USER_MODEL)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipend_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('intern', 'month')},
            },
        ),
    ]
