# Generated by Django 4.2.30 on 2026-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationotp_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationotp',
            name='purpose',
            field=models.CharField(choices=[('RESET', 'Password Reset'), ('VERIFY', 'Email Verification'), ('LOGIN', 'Login Verification')], max_length=20),
        ),
    ]
