# Generated by Django 4.2.30 on 2026-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_verificationotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_assign_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('MANAGER', 'Admin'), ('ADMIN', 'Super Admin')], default='INTERN', max_length=20),
        ),
    ]
