# Generated by Django 4.2.28 on 2026-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_phase2_part2_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='pdf_report',
            field=models.FileField(blank=True, help_text='Weekly report PDF file', null=True, upload_to='weekly_reports/'),
        ),
    ]
