# Generated by Django 4.2.28 on 2026-02-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0011_v2_schema_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_raw_text',
            field=models.TextField(blank=True, help_text='Raw resume text before parsing'),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL),
        ),
    ]
