# Generated by Django 4.2.28 on 2026-04-03 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0019_add_task_skills_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLAgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsilon', models.FloatField(default=0.8, help_text='Current exploration rate (epsilon)')),
                ('total_episodes', models.IntegerField(default=0, help_text='Number of tasks completed / policy updates')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('intern', models.OneToOneField(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='rl_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RL Agent State',
                'verbose_name_plural': 'RL Agent States',
            },
        ),
        migrations.CreateModel(
            name='QTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_key', models.CharField(help_text="Discrete state representation (e.g., '1|2|3...')", max_length=255)),
                ('action', models.CharField(help_text="Action name (e.g., 'EASY_TASK')", max_length=50)),
                ('q_value', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='q_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Q-Table',
                'verbose_name_plural': 'Q-Tables',
                'indexes': [models.Index(fields=['intern', 'state_key'], name='idx_qtable_lookup')],
                'unique_together': {('intern', 'state_key', 'action')},
            },
        ),
    ]
