# Generated by Django 4.2.28 on 2026-04-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_rlagentstate_qtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='self_rating',
        ),
    ]
