# Generated by Django 4.2.28 on 2026-04-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0021_remove_weeklyreport_self_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PHASE_1', 'Phase 1 — Standard Internship (Months 1–6)'), ('PHASE_2', 'Phase 2 — Stipend Internship (Months 7–12)'), ('FULL_TIME', 'Full-Time Employment')], max_length=20)),
                ('phase_start_date', models.DateField()),
                ('phase_end_date', models.DateField(blank=True, help_text='Null = currently active phase', null=True)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_score', models.FloatField(blank=True, help_text='ConversionScore.composite_score snapshot at the time of promotion', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='employment_stages', to=settings.AUTH_USER_MODEL)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employment Stage',
                'verbose_name_plural': 'Employment Stages',
                'ordering': ['-phase_start_date'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint Scanner'), ('FACE_RECOG', 'Face Recognition Camera'), ('RFID', 'RFID Card Reader'), ('QR_SCANNER', 'QR Code Scanner')], max_length=20)),
                ('location', models.CharField(blank=True, help_text="Physical location of the device (e.g., 'Main Entrance', 'Floor 3')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, help_text='IoT device identifier (populated only when source=IOT_DEVICE)', max_length=100),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False, help_text='True if check-in time was after the standard start time'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual entry by manager'), ('WEB', 'Web app self check-in'), ('MOBILE', 'Mobile app'), ('IOT_DEVICE', 'IoT biometric device')], default='MANUAL', help_text='How this attendance record was created', max_length=15),
        ),
        migrations.CreateModel(
            name='PhaseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.FloatField(default=0.0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('attendance_pct', models.FloatField(default=0.0)),
                ('weekly_reports_submitted', models.IntegerField(default=0)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('ai_decision_suggestion', models.CharField(blank=True, choices=[('PROMOTE', 'Promote to next phase'), ('EXTEND', 'Extend current phase'), ('DECLINE', 'Decline — end internship')], max_length=10)),
                ('decision', models.CharField(choices=[('PROMOTE', 'Promote to next phase'), ('EXTEND', 'Extend current phase'), ('DECLINE', 'Decline — end internship')], max_length=10)),
                ('manager_notes', models.TextField(blank=True)),
                ('criteria_snapshot', models.JSONField(default=dict, help_text='Snapshot of CertificationCriteria thresholds at evaluation time')),
                ('criteria_met', models.BooleanField(default=False, help_text='True if all active criteria thresholds were met')),
                ('employment_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='analytics.employmentstage')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_conducted', to=settings.AUTH_USER_MODEL)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='phase_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phase Evaluation',
                'verbose_name_plural': 'Phase Evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PHASE_1', 'Phase 1 Gate'), ('PHASE_2', 'Phase 2 Gate'), ('PPO', 'PPO Certificate')], max_length=10)),
                ('min_overall_score', models.FloatField(blank=True, null=True)),
                ('min_productivity_score', models.FloatField(blank=True, null=True)),
                ('min_quality_score', models.FloatField(blank=True, null=True)),
                ('min_engagement_score', models.FloatField(blank=True, null=True)),
                ('min_attendance_pct', models.FloatField(blank=True, null=True)),
                ('min_weekly_reports_submitted', models.IntegerField(blank=True, help_text='Minimum number of weekly reports the intern must have submitted', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active criteria set per phase is used for evaluation')),
                ('description', models.TextField(blank=True, help_text='Human-readable explanation of this criteria set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification Criteria',
                'verbose_name_plural': 'Certification Criteria',
                'ordering': ['-created_at'],
            },
        ),
    ]
