# Generated by Django 4.2.28 on 2026-04-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0024_add_weekly_report_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('performance_trend_score', models.FloatField(default=0.0)),
                ('absolute_performance_score', models.FloatField(default=0.0)),
                ('skill_growth_delta', models.FloatField(default=0.0)),
                ('manager_sentiment_trend', models.FloatField(default=0.0)),
                ('peer_comparison_percentile', models.FloatField(default=0.0)),
                ('composite_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('feature_vector', models.JSONField(default=dict)),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
