# Generated by Django 4.2.28 on 2026-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_resume_parsing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='List of education entries'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text='List of work experience entries'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='List of projects'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills extracted from resume'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text='List of tools and technologies'),
        ),
    ]
