# Generated by Django 4.2.28 on 2026-02-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_resumedata_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='applied_role',
            field=models.CharField(blank=True, choices=[('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('FULLSTACK_DEVELOPER', 'Fullstack Developer'), ('DATA_SCIENTIST', 'Data Scientist'), ('ML_ENGINEER', 'Machine Learning Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('MOBILE_DEVELOPER', 'Mobile Developer'), ('QA_ENGINEER', 'QA Engineer'), ('UI_UX_DESIGNER', 'UI/UX Designer'), ('PRODUCT_MANAGER', 'Product Manager')], help_text='Role the candidate is applying for', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='has_internship_experience',
            field=models.BooleanField(default=False, help_text='Whether the candidate has prior internship experience'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='internship_count',
            field=models.IntegerField(default=0, help_text='Number of internships completed'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='years_of_education',
            field=models.FloatField(default=0.0, help_text='Total years of formal education'),
        ),
    ]
