# Generated by Django 6.0.2 on 2026-02-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_resume_parsing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.FloatField(default=0.0, help_text='Technical skills proficiency score')),
                ('leadership_score', models.FloatField(default=0.0, help_text='Leadership and management potential score')),
                ('communication_score', models.FloatField(default=0.0, help_text='Communication skills score')),
                ('culture_fit_score', models.FloatField(default=0.0, help_text='Cultural fit assessment score')),
                ('ai_readiness_score', models.FloatField(default=0.0, help_text='Readiness for AI-assisted work score')),
                ('predicted_growth_score', models.FloatField(default=0.0, help_text='Predicted growth trajectory score')),
                ('skill_profile', models.JSONField(default=dict, help_text='Detailed skill breakdown by category')),
                ('domain_strengths', models.JSONField(default=list, help_text='List of strongest domain areas')),
                ('skill_gaps', models.JSONField(default=list, help_text='Identified skill gaps')),
                ('recommendations', models.JSONField(default=list, help_text='Personalized development recommendations')),
                ('risk_flags', models.JSONField(default=list, help_text='Risk indicators')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_intelligence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intern Intelligence',
                'verbose_name_plural': 'Intern Intelligence',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_vector', models.JSONField(default=dict, help_text='Binary encoding of skills')),
                ('skill_frequency', models.JSONField(default=dict, help_text='Frequency score for each skill')),
                ('tfidf_embedding', models.JSONField(default=dict, help_text='TF-IDF-like embedding for skills')),
                ('skill_categories', models.JSONField(default=dict, help_text='Skill counts by category')),
                ('skill_diversity_score', models.FloatField(default=0.0)),
                ('experience_depth_score', models.FloatField(default=0.0)),
                ('technical_ratio', models.FloatField(default=0.0)),
                ('leadership_indicator', models.FloatField(default=0.0)),
                ('domain_specialization', models.JSONField(default=dict)),
                ('experience_score', models.FloatField(default=0.0)),
                ('education_score', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='documents.resumedata')),
            ],
            options={
                'verbose_name': 'Resume Feature',
                'verbose_name_plural': 'Resume Features',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('snapshot_date', models.DateField()),
                ('total_interns', models.IntegerField(default=0)),
                ('high_potential_count', models.IntegerField(default=0)),
                ('avg_technical_score', models.FloatField(default=0.0)),
                ('avg_ai_readiness', models.FloatField(default=0.0)),
                ('skill_distribution', models.JSONField(default=dict)),
                ('experience_distribution', models.JSONField(default=dict)),
                ('domain_distribution', models.JSONField(default=dict)),
                ('at_risk_count', models.IntegerField(default=0)),
                ('risk_factors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('snapshot_type', 'snapshot_date')},
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
            },
        ),
    ]
