# Generated by Django 4.2.28 on 2026-02-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectassignment_status'),
        ('analytics', '0012_v2_field_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracking',
            name='project_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectassignment'),
        ),
    ]
