# Generated by Django 4.2.28 on 2026-03-10 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0016_alter_resumecertification_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Task difficulty level (1=easiest, 5=hardest)')),
                ('action_type', models.CharField(choices=[('EASY_TASK', 'Easy Task (Difficulty 1-2)'), ('MODERATE_TASK', 'Moderate Task (Difficulty 3)'), ('HARD_TASK', 'Hard Task (Difficulty 4-5)'), ('SKILL_GAP_TASK', 'Skill Gap Focus Task'), ('COLLABORATION_TASK', 'Collaboration/Team Task')], default='MODERATE_TASK', max_length=25)),
                ('skills_required', models.JSONField(default=list, help_text='List of skill names required/developed by this task')),
                ('estimated_hours', models.FloatField(default=4.0, help_text='Estimated hours to complete')),
                ('success_probability', models.FloatField(default=0.5, help_text='Baseline probability of successful completion (0.0–1.0)')),
                ('learning_value', models.FloatField(default=0.5, help_text='Expected learning value / skill growth potential (0.0–1.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RLExperienceBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(help_text='State vector at time of action (intern feature vector)')),
                ('action', models.CharField(help_text='Action taken (task difficulty or action type)', max_length=50)),
                ('reward', models.FloatField(help_text='Reward received after action')),
                ('next_state', models.JSONField(help_text='State vector after action was taken')),
                ('done', models.BooleanField(default=False, help_text='Whether this was a terminal transition')),
                ('reward_breakdown', models.JSONField(default=dict, help_text='Component-wise reward breakdown {completion, quality, growth, engagement, overdue}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='rl_experiences', to=settings.AUTH_USER_MODEL)),
                ('task_ref', models.ForeignKey(blank=True, help_text='Task this experience relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_experiences', to='analytics.tasktracking')),
            ],
            options={
                'verbose_name': 'RL Experience Buffer',
                'verbose_name_plural': 'RL Experience Buffer',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Normalized skill name (e.g., Python, Django)', max_length=100)),
                ('mastery_level', models.FloatField(default=0.0, help_text='Skill mastery level (0.0–1.0). 0=no knowledge, 1=expert.')),
                ('learning_rate', models.FloatField(default=0.1, help_text='How quickly the intern learns this skill (0.0–1.0).')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Profile',
                'verbose_name_plural': 'Skill Profiles',
                'ordering': ['-mastery_level'],
                'unique_together': {('intern', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role_title', models.CharField(blank=True, help_text='Cached role title for display without FK join', max_length=100)),
                ('milestones', models.JSONField(default=list, help_text='Ordered list of skill milestones to complete')),
                ('current_position', models.IntegerField(default=0, help_text='Index into milestones list (0-based)')),
                ('completed_milestones', models.JSONField(default=list, help_text='List of completed milestone skill names')),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='analytics.jobrole')),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'ordering': ['-updated_at'],
                'unique_together': {('intern', 'job_role')},
            },
        ),
    ]
