# Generated by Django 4.2.30 on 2026-06-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_resumedata_applied_role_and_more'),
        ('analytics', '0027_weeklyreportv2_ai_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracking',
            name='evidences',
            field=models.ManyToManyField(blank=True, help_text='Documents uploaded as evidence for this task', related_name='task_evidences', to='documents.document'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='The parent task if this is a subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='analytics.tasktracking'),
        ),
    ]
